on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

name: Deploy Prod Front-End
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Npm Install
        run: npm i --legacy-peer-deps

      - name: Build
        run: CI=false npm run build

      - name: Cache Project
        uses: actions/cache@v4
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Restore Cache
        uses: actions/cache@v4
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.GITHUBACTIONIAMROLE }}
          role-session-name: Github
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: build
          bucket: ${{ secrets.S3_BUCKET_DEV }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID_DEV }}
          invalidation: /*
